# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung//setup-makefiles.sh

# Config files can be on makefile
PRODUCT_COPY_FILES += \
    vendor/samsung/j5x-common/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/D05QL_s5k5e3yx_module_info.xml:system/etc/D05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/j5x-common/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/J05QF_sr552_module_info.xml:system/etc/J05QF_sr552_module_info.xml \
    vendor/samsung/j5x-common/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/samsung/j5x-common/proprietary/etc/V13QL_s5k3l2xx_module_info.xml:system/etc/V13QL_s5k3l2xx_module_info.xml \

# Prebuilts for j5xnlte
PRODUCT_PACKAGES += \
    camera.vendor.msm8916 \
    libAl_Awb \
    libAl_Awb_Sp \
    libTsAf \
    libaec_algo_front \
    libaec_algo_rear \
    libaf_algo_rear \
    libawb_algo_front_al \
    libawb_algo_rear_al \
    libchromatix_s5k3l2xx_common \
    libchromatix_s5k3l2xx_common_1080p_b \
    libchromatix_s5k3l2xx_common_1080p_s \
    libchromatix_s5k3l2xx_common_res0 \
    libchromatix_s5k3l2xx_common_res1 \
    libchromatix_s5k3l2xx_common_res2 \
    libchromatix_s5k3l2xx_common_res3 \
    libchromatix_s5k3l2xx_default_video \
    libchromatix_s5k3l2xx_golfshot \
    libchromatix_s5k3l2xx_hfr_1080p_b \
    libchromatix_s5k3l2xx_hfr_1080p_s \
    libchromatix_s5k3l2xx_hfr_120 \
    libchromatix_s5k3l2xx_liveshot \
    libchromatix_s5k3l2xx_panorama \
    libchromatix_s5k3l2xx_pip \
    libchromatix_s5k3l2xx_preview \
    libchromatix_s5k3l2xx_snapshot \
    libchromatix_s5k3l2xx_sports \
    libchromatix_s5k3l2xx_uhd_video \
    libchromatix_s5k3l2xx_zslshot \
    libmmcamera2_stats_algorithm \
    libmmcamera_cac2_lib \
    libmmcamera_wavelet_lib \
    libQSEEComAPI \
    libactuator_dw9806_camcorder \
    libactuator_dw9806_camera \
    libchromatix_s5k3l2xx_vt \
    libchromatix_s5k3l2xx_vt_hd \
    libchromatix_s5k5e3yx_wide_common \
    libchromatix_s5k5e3yx_wide_pip \
    libchromatix_s5k5e3yx_wide_preview \
    libchromatix_s5k5e3yx_wide_snapshot \
    libchromatix_s5k5e3yx_wide_video \
    libchromatix_s5k5e3yx_wide_vt \
    libchromatix_s5k5e3yx_wide_vt_hd \
    libchromatix_s5k5e3yx_wide_zslshot \
    libdiag \
    libdsutils \
    libidl \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera2_vpe_module \
    libmmcamera2_wnr_module \
    libmmcamera_dw_dw9806b_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hdr_lib \
    libmmcamera_image_stab \
    libmmcamera_imglib \
    libmmcamera_lsi_s5k5e3yx_eeprom \
    libmmcamera_rohm_brce064gwz_eeprom \
    libmmcamera_s5k3l2xx \
    libmmcamera_s5k5e3yx \
    libmmcamera_silicon_sr544_eeprom \
    libmmcamera_sunny_p12v01m_eeprom \
    libmmcamera_sunny_p5v23c_eeprom \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmipl \
    libmmjpeg \
    libmmqjpeg_codec \
    liboemcamera \
    libqcci_legacy \
    libqmi \
    libqmi_cci \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqomx_jpegenc \
    qseecomd
