# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8916-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter j53gxx j5lte j5ltechn j5nlte,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE := DaxUI
LOCAL_MODULE_OWNER := samsung
LOCAL_SRC_FILES := proprietary/system/priv-app/DaxUI/DaxUI.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := daxService
LOCAL_MODULE_OWNER := samsung
LOCAL_SRC_FILES := proprietary/system/priv-app/daxService/daxService.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := dolby_dax
LOCAL_MODULE_OWNER := samsung
LOCAL_SRC_FILES := proprietary/system/framework/dolby_dax.jar
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

endif
